### ISSUE TITLE
A question about code and data

### ISSUE THREAD

**Issue by dd-lucky** [TaoranJ/DMA-Nets#2]
Hello, I am very interested in your excellent work on AAAI-21. I would like to ask when the code and data set will be released on github?  Thank you very much!

**Comment by TaoranJ** [comment]
Thanks for being interested in our paper. The code and data will be uploaded Sept, well, hopefully early Sept:).  Just too busy recently.

**Comment by TaoranJ** [comment]
Datasets and codes are updated.
