### ISSUE TITLE
Do you have a plan to upload the data and code of your paper? 

### ISSUE THREAD

**Issue by liuhuijun396** [TaoranJ/DMA-Nets#3]
Hi, I have read your paper Dynamic Multi-Context Attention Networks for Citation Forecasting of Scientific Publications, and I have a very strong interest in this novelty work. But I have no ability to obtain the results of your experiment. Do you have a plan to upload the data and code of your paper? Thank you very much.

**Comment by TaoranJ** [comment]
Hi, I'll definitely submit both code and data in December. I'm working on my graduation since Sept, so everything other things are ridiculously delayed.

**Comment by TaoranJ** [comment]
Datasets and codes are updated.
